// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrZ7O0LI9IQA4o654yZ2p5kjubrXOteuY',
    appId: '1:585658846353:web:3780e0bb0fa88b685b8330',
    messagingSenderId: '585658846353',
    projectId: 'test-879c6',
    authDomain: 'test-879c6.firebaseapp.com',
    databaseURL: 'https://test-879c6-default-rtdb.firebaseio.com',
    storageBucket: 'test-879c6.firebasestorage.app',
    measurementId: 'G-BFVWJDN4QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdotbs0ZPEguD2lKGqGa0HR5KKdcIpnOM',
    appId: '1:585658846353:android:33bf518be74a5ae45b8330',
    messagingSenderId: '585658846353',
    projectId: 'test-879c6',
    databaseURL: 'https://test-879c6-default-rtdb.firebaseio.com',
    storageBucket: 'test-879c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo_ODdrhb2Yc-6SCBYJqdThrAAjb-2F14',
    appId: '1:585658846353:ios:0b0dfa7206d17d145b8330',
    messagingSenderId: '585658846353',
    projectId: 'test-879c6',
    databaseURL: 'https://test-879c6-default-rtdb.firebaseio.com',
    storageBucket: 'test-879c6.firebasestorage.app',
    iosBundleId: 'com.example.feed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo_ODdrhb2Yc-6SCBYJqdThrAAjb-2F14',
    appId: '1:585658846353:ios:0b0dfa7206d17d145b8330',
    messagingSenderId: '585658846353',
    projectId: 'test-879c6',
    databaseURL: 'https://test-879c6-default-rtdb.firebaseio.com',
    storageBucket: 'test-879c6.firebasestorage.app',
    iosBundleId: 'com.example.feed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA05IFVev9fBGpLYIdhiWyHW9LqGhiVOZo',
    appId: '1:585658846353:web:6e1f37cd1909fc785b8330',
    messagingSenderId: '585658846353',
    projectId: 'test-879c6',
    authDomain: 'test-879c6.firebaseapp.com',
    databaseURL: 'https://test-879c6-default-rtdb.firebaseio.com',
    storageBucket: 'test-879c6.firebasestorage.app',
    measurementId: 'G-1YH9CWPLV8',
  );
}
